#ifndef VIDEOCOMPUTEPIPELINE_CONFIG_H
#define VIDEOCOMPUTEPIPELINE_CONFIG_H

#define PROJECT_NAME "VideoComputePipeline"
#define PROJECT_VERSION "0.1.0"

#define DEFAULT_INPUT_PATH "data/input/15592600_3840_2160_60fps.mp4"
#define DEFAULT_OUTPUT_PATH "data/output/output.mp4"
#define DEFAULT_BENCHMARK_PATH "benchmarks/results.csv"
#define DEFAULT_ENCODER_NAME "libx264"

#define DEFAULT_MAX_FRAMES 0
#define DEFAULT_ENABLE_BENCHMARK 1
#define DEFAULT_LOSSLESS_OUTPUT 0
#define DEFAULT_MEMORY_BUDGET_MB 0
#define DEFAULT_FRAME_SLOTS 3
#define DEFAULT_DECODER_THREADS 4
#define DEFAULT_ENCODER_THREADS 4
#define DEFAULT_PROCESSOR_WORKERS 2

#define VCP_MAX_PATH_LENGTH 1024

#endif
