#ifndef VIDEOCOMPUTEPIPELINE_CONFIG_H
#define VIDEOCOMPUTEPIPELINE_CONFIG_H

#define PROJECT_NAME "VideoComputePipeline"
#define PROJECT_VERSION "0.1.4"

#define DEFAULT_INPUT_PATH "data/input/15592600_3840_2160_60fps.mp4"
#define DEFAULT_OUTPUT_PATH "data/output/output.mp4"
#define DEFAULT_BENCHMARK_PATH "benchmarks/results.csv"
#define DEFAULT_DETECTIONS_PATH "benchmarks/detections.csv"
#define DEFAULT_MODEL_PATH "models/yolov5s_trt11.engine"
#define DEFAULT_LABELS_PATH "models/coco.names"
#define DEFAULT_ENCODER_NAME "libx264"
#define DEFAULT_OUTPUT_FORMAT "auto"

#define DEFAULT_MAX_FRAMES 0
#define DEFAULT_ENABLE_BENCHMARK 1
#define DEFAULT_LOSSLESS_OUTPUT 0
#define DEFAULT_MEMORY_BUDGET_MB 0
#define DEFAULT_FRAME_SLOTS 3
#define DEFAULT_DECODER_THREADS 4
#define DEFAULT_ENCODER_THREADS 4
#define DEFAULT_PROCESSOR_WORKERS 2
#define DEFAULT_DETECTION_CONFIDENCE 0.25f
#define DEFAULT_DETECTION_IOU_THRESHOLD 0.45f
#define DEFAULT_INFERENCE_INPUT_SIZE 640
#define DEFAULT_INFERENCE_BACKEND "tensorrt"
#define DEFAULT_INFERENCE_PRECISION "fp16"
#define DEFAULT_DETECTION_CLASS_COUNT 0
#define DEFAULT_MAX_DETECTIONS_PER_FRAME 300
#define DEFAULT_PROGRESS_INTERVAL 300
#define DEFAULT_FFMPEG_LOG_LEVEL "warning"
#define DEFAULT_VIDEO_DECODER "cpu"
#define DEFAULT_DECODER_FALLBACK "cpu"
#define DEFAULT_DRAW_BOXES 0
#define DEFAULT_BOX_THICKNESS 2
#define DEFAULT_BOX_CONFIDENCE 0.0f
#define DEFAULT_BATCH_SIZE 1
#define DEFAULT_INFLIGHT_BATCHES 1
#define DEFAULT_AUTO_TUNE 0
#define DEFAULT_PROFILE_HARDWARE_ONLY 0
#define DEFAULT_TARGET_FPS 0.0f
#define DEFAULT_VRAM_BUDGET_RATIO 0.375f
#define DEFAULT_VRAM_RESERVE_MB 0
#define DEFAULT_PIPELINE_OVERLAP_MODE "auto"
#define DEFAULT_PARALLEL_INFERENCE_MODE "auto"
#define DEFAULT_INFERENCE_CONTEXTS 1

#define VCP_MAX_PATH_LENGTH 1024
#define VCP_MAX_CLASS_FILTERS 128
#define VCP_MAX_CLASS_NAME_LENGTH 64

#endif
